### ISSUE TITLE
Required field for Async-select

### ISSUE THREAD

**Issue by luckylwk** [luckylwk/hoppin-design-system#14]
Currently not working. It is required, but doesn't pick up on a value being there

![image](https://user-images.githubusercontent.com/6073340/68899363-7e15b380-06ff-11ea-8148-f7d5451397a6.png)

<img width="306" alt="image" src="https://user-images.githubusercontent.com/6073340/68899379-85d55800-06ff-11ea-8db0-89d72cf777cb.png">

**Comment by luckylwk** [comment]
Can you have a look at this @jonashaefele . Adding a required field for async-select does not work currently

**Comment by luckylwk** [comment]
So what I am experiencing is the following: Whenever the scheduler opens there are two starting scenarios: either there is already a `meeting_address` value or the value is an empty string.

### Option 1: Value preset
When the value is set the form (and the field is flagged as required) the form does not want to proceed: 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/6073340/69978555-ab81a000-14fa-11ea-9744-07cb6c2461a6.png">

When I then change the value (using the google search) is still does not allow to continue:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/6073340/69978621-c8b66e80-14fa-11ea-9368-be53d1aea03e.png">

### Option 2: No value (empty string)
Same behavior when changing the value
<img width="645" alt="image" src="https://user-images.githubusercontent.com/6073340/69979004-6dd14700-14fb-11ea-863a-9ee6c277e0fa.png">

Do we have to add a manual validation function inside the field specification, or can we update the HDS to validate (what is a 'neater' solution at this stage?).
![image](https://user-images.githubusercontent.com/6073340/69979096-a5d88a00-14fb-11ea-9fa6-5ca9f7af3f4a.png)

**Comment by jonashaefele** [comment]
I think what happens is that the frontend changes, but the data (state) doesn't. Hence the onChange handlers not getting called and the required check not updating.

Shouldn't need a validate function. That is on top of the required check, not instead of.

Probably soemthing to do with all the filters like these:

https://github.com/luckylwk/hoppin-design-system/blob/v0.4.11/src/components/Form/Fields.js#L88

https://github.com/luckylwk/hoppin-design-system/blob/v0.4.11/src/components/Form/Fields.js#L142
